env:
  global:
    - secure: h7Z35jo9OYoZbB5vjl2sb4HGDHBriIt37k59sDvWswVvrsH/E3cK/AdgD9/w+IgKNzqFTOv3cK+24b3WJ/U2HKwVsJ6IOJHZQ+mNZv+Wa812NT4Zx4y5rgBgBrHtSDl826w/+jsAQjsesAXcv/CflY7OOhKNllB+Q7l4ImjTS+YMxN7rzlKMq6Qff+qn4eL5ju1hfKy3aseY0wdNycDvQFpsaRYvj1e55+LZkp+lQJ2XawV7hQNr5en4885FZ3dNB7gKC690xYbYIAdjn1RAuj/rSQmibO+fK8g58wL3h7Y8hgcL+o0SrLUkcdpIRq+7b3omM0WaAvKYsYZ5hauPQvrssmrXJ0pMrqPsb5ps1SEQX+MvB01GPHi8D2G53UZipAgOT7UDTZSEyUh5a5S04wq1VHqZpvkI70jpgNI3mhJ80B/1TBjFPdyip/d2XXeCFz7ThDjM+fstHig5IUqTfBhXxw2qAFgXWHFL//+GQVWXkfiXKsVevYPHFO6qmZpwwQwZeot1eCe4lpZOhsNBzH/cuq6lkvoAIV4UyzKNXEfCkO3k0q62CnrH0qfhGwE0lsYy2ZeJzqITqoakAFspI5VPEnYARtAVi+Rhfug/hzaAMsfVuhTui1J7hoCkKibNJwEsNBYquKx0Yh1iBu9lNOVzJJQ1fFQj2+YIpSJfev4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
