env:
  global:
    - secure: kV3DevreOquAqqCx3DnMi2tKEZupXNvciG1JVBkatoQ3kr3JK1dM3/B+/bJzvaCQGPmJC25VhqOKJLGETRCvSvilf7gRVwKsO2N0dG8IkTEFXV/ab7ckVWI8zMcGHdUe2dfyd/Jr0ntfRgHhkUf16Kxsnj9ODSFTo+EIAtoUrOiXOLhCqhtCl37Cu7m9ZGSFkzsHupPiqzs/6GKDFfXKIVdk796lX/Nk+HT27sWsgNTxOsf+yvhYTiDZwEpkpND6URN30VzEZ/lpzjWXJiiLFxXbpOJt4ayTr65dEYuGTrr+bqQc5FgNFBeEttEzVbrJnE7dyAAsTv7U+x/NoYDLkN7FhCuBeB6HQIgv7CPaZp/80qySb+JeE2bTMOEsR+GD7NXWt6O8BpeJxWpshmL/b8iZjGn/Hcd1QrIYjevLWUnL/KeUZTcLjg3lMDsyiZehv2bLer5bH0CTjfcgRI1Y4DwYJVTMoBT58aHl6gsC58BCxze8eDPAuIaU83So/k+S0M45OUUC0xjmXGCvAedJcKl+9AHqksp4L3KGTsF//78gVHjhr5hl/JKhYd1pMwghgAyh7udJehC2D0Pz89RaPEx7NvMo3Gjp5xcEJYefgoQdIeb7l/N1Bkjyyj+8OgSCz2ZIS5YCFRQfz7aoYVtFnnemSmi/d6FKMh6xqWpHTco=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
