env:
  global:
    - secure: m3U+fq+2dIdXus5Boz/M4m894aPslcv3s7H3JdzduMEkzjBDeiieSBfl1KLrZp/Oem48VFq44T8LbFAvzyEPoUhCXuUfKsNa+OG9OsQh1jXgZcJ7q4NxElgLZCOIQNFegmlI19ZZtdsOxWSD/KPbDgp+yhaAxQ7Lnd3XVTVV3ANGDMUwOUj5ozyhjiGjZAV2j3ZwkRLAWYMBs0OEl9rUj3bLzoDbhm0SOLEkSD3nUrL5vbMCAkQLkxieJEGiEEBXMTR8OL13m7TcdLy2FrzOuUvBF4qclI5mfMCxwDLS0Tm24c/8sc4DiWD6pES3Z3Gx4hHYEeDSpNoFNLoncMtdNlQUko16fa41/2ak4qdy+z1EwKR0ZUfvYrjEt8fRu0FEe8lwSN7yyDlhwLxqzY/RocHYBKr/9r8i9S1ET58Ljq592QKA8IyXW1tVgIvMfqsZkXF3wZZKQ4JMpb/QJ5PL+RZbNwz1R9KwwmfikmeO8qcQVmnGaRSI1xADeg6uAWoaakjHkQZStKgeUYK+ciOR++YMViI4k1QB6a0cW3dBporQpn1Qp6cslzAnVHTUHtJSVpFR2BB7Z/6RQ0kflsIC778rAcKjSS2EuN5EFG2GAatfEzdJSL4r2UcsqpfG6mHbio/BWvw3LBN5aLiOqsDByxUWvAxG9Y6LU1LW3JHuiC4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
