env:
  global:
    - secure: BC9yB8NIChJngN49KTIuNclspI18j8G8VIfekw1zlfGYKJYdMYnnPESF8+ecZUTpz8hKYql7fMltC9bVEMTDMRJ2BJMkNcDsosCXzXTPSuAoLd8NOEsQYePqu5SBvddpsmCxwg1r2qPaE/UVEarOZt85bn7IKRiFuMVdChsYXn99m7n9D08CdhpYVrOdV6jl0Dwf4XtTWMk5aWX/L543FZWuX9vXsqU5DS+sdFlhjD+q5xh2AfBszSYSfOiz5T+cDV3NbOKIPewhYnhQyXXd7haqCsjLdVoU19YMr9vN5kHrtfFoVSLhYi+5B1zdazO5FSXCvivJWCPWxK3GU1ovvsKwwMyHm2KdFaSnxtfMpYpRo6n0M4hhK6tzhbMk1A/EUZUYa8Ddxmwi2Eoz8uOxucDOLx6uymhMDwAMqw3yqU8IoSynO3KFqeuvke0zUAPZRy3qK80gazch1e082f0eNPZSECjYGUXL70GIERe00qm0/JFYqUjICL+/ftkrc+7vZA7FMU/kEvaUjXb6WwNCGZLMeLsPk5r1gE+12Z83T/Iv29Owuw/Ig8y6+nVLXX2MgTtQuYDj/V2zNRm6A/CUuNEqPRirOuPo81J5qA0dZ2pwDeMm5d24s4nJmgay01zuiT3thfYsks7TPTfEAPYWqrQkYn+YWTOrsWLfWfdjA7E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
