env:
  global:
    - secure: UVziDZZ3h8BPSGdAa6ZHzgR86C7xTi6xqYWrn7yh8Bfr+PGTmG/fxbSt6RUUG+nLEau/U6MAjtvJfXGNK92/b9LMrScMSIV8HMrmgPC+dIInocjR2+g8ZWhMo+rb8Alem9YktLJ6nxGQOguUAFBpvvLpb2wRq2v4985NdCfyjvOih9WjUs4fEeDnfxiDBYVBpQi4I+o6XzfaMApWkPGUl8XwBXb42W/+7P+qCCnTAqNBE1XSk3+1sj52jPidamha4DK9UIlCsigYaBWesuqINBioGVdezX2/qfsbAT28Qj9mPueHO27thVOlmcvkZ1a1F4VoCRz/mH7n/Ygj8Xz8JxtQByXOnB0bwDcX5GHYACcCmu5HF0HPT7zJTCtZ1Jyd6YxEpuBATy7MN0L1o3WSVyYOolecu/KwqYdhSUOKk4vhXjIu1vbKPRUQ2NQvjM0Snlabb28UXpHUxgnyWHZm9fAjvmfIvtQje1GwkoxBcRKbv6N2mMeHfb+f3WuYvn38LdSdZtHtRTuqutAYCsy/PGYHAb19wEuP+QDHf3mZioDmOYbjX3tQ84vDg3slplQhXRC9k7TuFhu3wH1ALXfbkNB8LEGpplPcyVAz7RjrCHqnPyZZi5+U5VdlMETW8azztwfmbI7Vu5fZC7IofunztArRexHPxYFtfbboY3dsGCE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
