env:
  global:
    - secure: bsnfJOS8FcGo73hO6WmOD9hu8l/DXD1xLZztE1Qa/yDt3XXUpbS6CXLpxgufBy1DIGcjEeGMKsLcAzj6HDscbdj4iV8G9QDzWgAP1+TkAwflutCTgJbns6/5OZ1C6/54eH4PQwcJThaGnrRlMYCrLeCBvG6aOmEPOorDO5sXxkCzrjLbGhpux0ysEmCvIC+/es8YlAamZGaI3n/BiLzOnpqA5hjxXXqyiCAImC6JkHViwhp0hee1pcthlb86U8whRefr5cKriRbECtWqGei9PZlDJFfLAlpTUY1CeJQlcRL2aqb/Rv1C13vidTftpT8ttpRqHkfsvs5wt6yhPoamV6vZVFZJHPfmbKCSeXxKhxp0xEX5UKQ7BYZB6Bf4vBH80rGE161nQC9kz+Zq068M5yPEhZQOkBzZcO+ATUR+vyeydEY6l2pvSkElwQV7rLKf2exWsvdp2TpqKS54o7B67xmQxMOk/WDFPSGLG66UFvWf8BHXPDLF1wdrBp1ea3KBgvAD4+Q6U2rPEDzLqcqeGFi3008QXd3FAWStvDMkHdvxbVUQBZU1OeFAsx7kTYETY774Jk6wMNM4lX9/+ufu2HXkfhGdh7pJkfpuOpB+Q6VObBnyL89ik0uzEOmSb6lTNgqOqziuqLa4VKXzcgu4adf+0pbdJSLntIBMRSSAclw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
