env:
  global:
    - secure: Iy2gEC5OR4vPCRMeyFNVHwSc6WNJQxGUkWB7fbKpaES1pv76mmcS8wctRX5QbnQa9pcsLF38cJmaUC5Z07aQE8DmXcOJ2J4ejucsXtQkCG8PV9oFDISGwaap0WuzWyx4VwYd7FX2eSFrb61qCqU/UbRtyuTZA3s9ShKnCI2Vnk+A8RBD0d4HK3V5chrnjdKfNIQNCZnKGigONI7tFryWhTCzoFMtdjSjGdDULS3FeTkyu5o61rS2FQqT6Up8mRQm78mlRKWwWDshgXHVPw6WXpxOVd1nRu1+As/eaThV5sS2cZhhLb1Vofv9yvKr80u/2NQntrllJj30UAniQx5Dggtp+0+NVrhR2vZQ1lm7jmQb79O4HOHf7X0tD+2l+uBj5Q3rdHCfPODCvQW9Chtofp+PFlxVlE/6pD/endGasLTVePmooBMJgNhG1p+MAwfvRqkSCh14k6NJbcqX9bHpLHwKBjAE5gSemhKXPFFxndZbNciUoFB27RRt6Ga/0i487LvXVc/XIPx6d85qXnHzvDqNceu8wtFZ+DXzqseBazZROP3bAB5G/UrqWnIjGSWudyWkirdbzZIdMhwdTlE/bsPukDsmYR58oCrX7x63kVrCQRriPdki3Tf0SHrJwfIU/x/MAqprV1gnO6RRTubO93ANACRDHG/OGbaGzhixtr8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
