addons:
    apt:
        packages:
        - dos2unix
env:
    global:
    -   secure: iX9zHiiZw4kdnYlgRFVjY58UMkwnAwWl49GSSwwQf1v8rr6vI15MXNIIkKYgWSVkDVIPzf1+9wRa388StKzUcN0d2DmoV+MZPo2zEpIs94Heqo1McGUM9LeQGkM3kNRv3e3T++ia0UjkMjEjsybwvSw0CSwqLOhwwB60fO5BXcA+n0Bu0BLNbV1iOwHToG0rbPa6rADWfnpVd0ouBlSLUmprYR6FJ23wQrfOzhv33R/Xe3ObCf5GeyYm3+EM4ko61C0Bi6kf1mFnt/0SgAWPQmJAZ1lI8LLj3qkCY6gozTbwjPKaPhaRwIMlwDW17tdfcDWNZAp1rDrVWhRkfCaYb+9oyuGmeAl+GtF6Q459dhd0Mg1unwQ9djqQ7sZLr4pRvipvBCvx/NJaJ3H+k8BA3QYF9IUminxVWl6QNM2yfpih9c8w/pCTk2Bu982TqyKUDjoq5zEpOxI/hpqptjYzYUFYXmEw1DkT8+2cKHyMJJs5nkC04x0ejGZ4GxHM6i5E0klQZ9J0Pj9zqThtuByIcX33fcuyOXD1HREUxfLAis0pZoxQDacV2HJWDxqj09JpOXWsP1V/Ja76LngpdnEYM5YQB9I9QOD8x/KYzfjmosan4EJGIYJhlMc0SpxNQ7AUkr3nSJyy2NlytI87kBn16xryeiZA7Rz/aYvYhX9fmZE=
    -   GIT_NAME: Travis CI
    -   GIT_EMAIL: dead-hosts@funilrys.com
    -   GIT_BRANCH: master
    matrix:
    - PYTHON_VERSION="3.7.3"
install:
- export PATH="${HOME}/miniconda/bin:${PATH}"
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p ${HOME}/miniconda
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n launcher-environment python="${PYTHON_VERSION}"
- source activate launcher-environment
- python -VV
- pip --version
- pip install dead-hosts-launcher
- rm miniconda.sh
language: generic
notifications:
    email:
        on_failure: always
        on_success: never
        recipients:
        - dead-hosts@outlook.com
os:
- linux
script:
- dead_hosts_launcher --version
- dead_hosts_launcher
