env:
  global:
    - secure: CcYWV0B2KzeMoSnZ8TQ0zzEkpSzsxs9b+Tx1BPuTgxeseB60kwStnahIciHKb+jPFwJB3EmSEuPnI+8icxol6w9u044lUPM/awBLq4Sb/cl/+PF9nsj7Sz/6zJBRryLFKRr6EgJfkFWjkKcT3e4Un6/pPznvYN2VygoFBwDV90Ei6cj1xzc1nuhSfT/mXrnNe06hZHL7UJVKpVYNIzLE7vLap2v+FAsD6fIpjyrfU1Cs/DuZi4h5j24cpYJCwsGhMv9xSJ2dFq80M0DsSgvpGsU198ZjwSe5QQAPyy58lOCZm08Ul3hyArz4lhNvSXjcWCGYqGLZRsi9SMDkHqH09Nwo2XOp70GH5WKAjnCofoLN+ez9dnMjuFS4OFlau+K0Oxiq3oG4Jgu1kqFKrP59eBu2VZ4Rr8EChx7CG0swL8ffKQnnHfLHAHe6RCMwa8fSpdcPyGZO44jLnTAocpfbhcTdOZQ3wI8oioeTuGPdBFHXbk8YOibimBSMEpXlE1PmmYAuqu9XSBTTO8nCKnQR8AY0Z5kF0zSMd3xPdXZWOkgFipNZ+gMPpTlZuJQDiR1tB27nVSwJFxWx+9yjvhOMeIi3V5HBTLYuXA3fCuU6seXFoWU+lU4eDvCOcnd5e2yX01lrpUGsvJGxH0cxzyYQgdQhPF02X2ZKwiRS6UGDTRM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/hosts_git_StevenBlack
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
