cli_decoding:
    adblock: false
    adblock_aggressive: false
    rpz: false
    wildcard: false
cli_testing:
    autocontinue: true
    chancy_tester: true
    ci:
        active: true
        branch: master
        command: hash dead_hosts_launcher && dead_hosts_launcher --save
        commit_message: '[Autosave][Dead-Hosts::hosts_git_StevenBlack]'
        distribution_branch: master
        end_command: hash dead_hosts_launcher && dead_hosts_launcher --end
        end_commit_message: '[Final/Result][Dead-Hosts::hosts_git_StevenBlack]'
        max_exec_minutes: 20
    cidr_expand: false
    complements: false
    cooldown_time: 0.2
    days_between:
        db_clean: 28
        db_retest: 1
    db_type: csv
    display_mode:
        all: true
        colour: true
        dots: true
        execution_time: true
        less: false
        max_registrar: 15
        percentage: true
        quiet: false
        registrar: false
        simple: false
        status: all
    file_filter: null
    file_generation:
        analytic: true
        hosts: false
        merge_output_dirs: false
        no_file: false
        plain: true
        unified_results: false
    hosts_ip: 0.0.0.0
    inactive_db: true
    local_network: false
    max_workers: 5
    mining: false
    preload_file: false
    sorting_mode:
        hierarchical: false
        standard: true
    testing_mode:
        availability: true
        reputation: false
        syntax: false
    whois_db: true
collection:
    preferred_status_origin: recommended
    push: true
    url_base: https://collection.dead-hosts.funilrys.com
debug:
    active: false
    level: info
dns:
    delay: 0.0
    follow_server_order: true
    protocol: UDP
    server:
    - 8.8.8.8
    - 8.8.4.4
    trust_server: false
http_codes:
    list:
        potentially_down:
        - 400
        - 402
        - 404
        - 409
        - 410
        - 412
        - 414
        - 415
        - 416
        - 451
        potentially_up:
        - 0
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 307
        - 308
        - 403
        - 405
        - 406
        - 407
        - 408
        - 411
        - 413
        - 417
        - 418
        - 421
        - 422
        - 423
        - 424
        - 426
        - 428
        - 431
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        - 506
        - 507
        - 508
        - 510
        - 511
        up:
        - 100
        - 101
        - 102
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 429
    self_managed: false
links:
    api_date_format: https://pyfunceble.funilrys.com/api/date-format
    api_no_referrer: https://pyfunceble.funilrys.com/api/no-referrer
lookup:
    collection: true
    dns: true
    http_status_code: true
    netinfo: true
    reputation: false
    special: true
    timeout: 5
    whois: true
max_http_retries: 3
proxy:
    global:
        http: null
        https: null
    rules: []
share_logs: false
user_agent:
    browser: chrome
    custom: null
    platform: linux
verify_ssl_certificate: false
minutes: 15

    # Sets the working branch. This is the branch from where we are testing.
    branch: master

    # Sets the distribution branch. This is the branch that is going to get
    # the (final) results.
    distribution_branch: master

    # Sets the command to execute everytime before each commits except the last
    # one.
    command: null

    # Sets the command to execute before the last commit.
    end_command: null

  display_mode:
    # Provides everything related to the display mode.

    # Activates the printing of dots.
    dots: False

    # Activates the printing of the execution time.
    execution_time: False

    # Activates the output of the percentage information.
    percentage: True

    # Activates the output of the top registrar information.
    registrar: False

    # Activates the quiet mode.
    quiet: False

    # Activates the output of very few information.
    less: True

    # Activates the output of all information.
    all: False

    # Activates the output of the status and it's status (only)
    simple: False

    # Activates the coloration of stdout.
    colour: True

    # Sets the status do display to STDOUT.
    # NOTE: This does not have any effect with the generated files.
    # Available values: ALL | ACTIVE | INACTIVE | INVALID | SANE | MALICIOUS
    status: all

    # Sets the maximum number of registrar to display.
    # NOTE: This does not have any effect with the generated files.
    max_registrar: 15

  testing_mode:
    # Provides all available testing modes.
    # WARNING: Only one can be used at a time.

    # Activates the availability test.
    availability: True

    # Activates the syntax test.
    syntax: False

    # Activates the reputation test.
    reputation: False

  days_between:
    # Provides everything which is x days periodic.

    # NOT IMPLEMENTED (Anticipation for future usage).
    db_clean: 28

    # Provides the number of days to wait before retesting subject which were
    # stored into the inactive database.
    db_retest: 1

  sorting_mode:
    # Provides all our sorting mode.
    # WARNING: The sorting mode is only applied to the files. NOT STDOUT.

    # Activates the hierarchical sorting.
    hierarchical: False

    # Activates the standard sorting.
    standard: True

  file_generation:
    # Provides everything related to the generation of file.

    # Deactivates the generation of any status file.
    no_file: False

    # Activates the generation of the hosts file(s).
    hosts: False

    # Activates the generation of the plain (or raw) file(s).
    plain: True

    # Activates the generation of the analytic file(s).
    analytic: True

    # Activate the generation of an unified file for the copy of what is
    # outputted to STDOUT.
    unified_results: False

    # Activates or disables the merging of the results of all inputted files into
    # one single output subdirectory.
    merge_output_dirs: False

lookup:
  # Provides everything related to the lookup.

  # Activates the usage of the DNS lookup.
  dns: True

  # Activates the usage of the HTTP status code lookup.
  http_status_code: True

  # Activates the usage of the network information socket.
  netinfo: True

  # Activates the usage of our special rules.
  special: True

  # Activates the usage of the WHOIS record.
  whois: True

  # Activates the usage of the reputation data reputation.
  reputation: False

  # Activate the usage of the collection.
  collection: False

  # Sets the timeout to apply to each of our lookup tools who support a timeout
  # option.
  timeout: 5

dns:
  # Provides everything related to the DNS lookup.

  # Activates the follow-up of the given order.
  follow_server_order: true

  # Activates the trust mode. Meaning that if one of the DNS give us a negative
  # response (without error), we take it as it is.
  # When this mode is deactivated (false), when one of the DNS give us a negative
  # response (without error), we still ask all other servers.
  trust_server: false

  # Sets the list of server to communicate with.
  # It must be a list.
  #
  # WARNING:
  #   IPv6 should be given in this format if a port is explicitly given:
  #     [ip]:port
  #   If you omit the braket, the port will be set to the default one (53).
  #
  # As example:
  #   - first.dns
  #   - second.dns
  #
  server: null

  # Sets the protocol to use.
  # Available: UDP | TCP | HTTPS | TLS
  protocol: UDP

  # Sets the delay (seconds) to apply between each queries.
  # When a value > 0.00000 is given, we will wait for the given amount of
  # seconds between each queries.
  delay: 0.0

# Not Implemented yet. Reserved for future usage and implementation.
share_logs: False

user_agent:
  # Provides everything related to the user agent choice.
  # Note:
  #   Please report to https://git.io/JLWe5 for more insight about the
  #   browser and platform available..

  browser: chrome
  platform: linux

  # Sets the user agent to use.
  # WARNING: If given, this will be used systematically.
  custom: null

proxy:
  # Provides everything related to the proxy.
  #
  # The idea:
  #   We have two main keys, "global" and "rules".
  #   The system will always follow the global keys unless you define an explit
  #   TLD.
  #
  # Example:
  #
  #   Let's say we want all HTTP requests to go through example.org but we want
  #   all HTTP request for domains ending with `.com`, `.org` and `.dev` to go
  #   through example.com. And, we want all domains ending with `.onion` to go
  #   through example.dev.
  #
  #   This is how it will look like.
  #
  #       global:
  #         http: http://example.org:8080
  #         https: http://example.org:8080
  #
  #       rules:
  #         - http: http://example.com:8080
  #           https: http://example.org:8080
  #           tld:
  #             - com
  #             - org
  #             - dev
  #         - http: socks5h://example.dev:8080
  #           https: socks5h://example.dev:8080
  #           tld:
  #             - onion
  #

  global:
    # Global HTTP proxy to use when no rule is given or matched.
    http: null
    # Global HTTPS proxy to use when no rule is given or matched.
    https: null

  rules: []


# Activates the verification of the certificate.
verify_ssl_certificate: False

# Set the maximum number of retries to perform.
# This should be an integer >= 0.
max_http_retries: 3

http_codes:
  # Provides everything related to the HTTP code lookup interpretation.

  # Informs PyFunceble that the end-user (not PyFunceble) is managing this list.
  # This means that you won't get any update in this section.
  self_managed: False

  list:
    up:
      - 100
      - 101
      - 102
      - 200
      - 201
      - 202
      - 203
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 429
    potentially_down:
      - 400
      - 402
      - 404
      - 409
      - 410
      - 412
      - 414
      - 415
      - 416
      - 451
    potentially_up:
      - 000
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 307
      - 308
      - 403
      - 405
      - 406
      - 407
      - 408
      - 411
      - 413
      - 417
      - 418
      - 421
      - 422
      - 423
      - 424
      - 426
      - 428
      - 431
      - 500
      - 501
      - 502
      - 503
      - 504
      - 505
      - 506
      - 507
      - 508
      - 510
      - 511

links:
  # Provides some of our API links.
  # NOTE: Not implemented yet as the underlaying infrastructure will be
  # rewritten.
  api_date_format: "https://pyfunceble.funilrys.com/api/date-format"
  api_no_referrer: "https://pyfunceble.funilrys.com/api/no-referrer"

collection:
  # Provides everything related to the collection.

  # Provides the base of the URL to access to communicate with the collection.
  url_base: https://collection.dead-hosts.funilrys.com

  # Activates the push of dataset into the collection.
  # WARNING: This is useless, if you don't have an API Token set as the
  # COLLECTION_API_TOKEN environment variable.
  push: False

  # Sets the preferred pull origin.
  #
  # When choosing, `frequent`, the system will pull the most frequent status
  # that is provided and calculated by the collection.
  #
  # When choosing, `latest`, the system will pull the latest status that is
  # provided and available into the collection.
  #
  # Available: frequent | latest | recommended
  preferred_status_origin: recommended
